link_spheres:
  base_link:
    - {x: 0.075, y: 0.075, z: 0.1, radius: 0.2}
    - {x: 0.075, y: -0.075, z: 0.1, radius: 0.2}
    - {x: -0.075, y: -0.085, z: 0.15, radius: 0.2}
    - {x: -0.075, y: 0.085, z: 0.15, radius: 0.2}
    - {x: 0.0, y: 0.19, z: 0.2, radius: 0.1}
    - {x: 0.1, y: 0.165, z: 0.2, radius: 0.1}
    - {x: 0.165, y: 0.085, z: 0.2, radius: 0.1}
    - {x: 0.185, y: 0.0, z: 0.2, radius: 0.1}
    - {x: 0.1, y: -0.165, z: 0.2, radius: 0.1}
    - {x: 0.165, y: -0.085, z: 0.2, radius: 0.1}
    - {x: 0.0, y: -0.19, z: 0.2, radius: 0.1}
  fixed_torso_link:
    - {x: 0.15, y: 0.4, z: 0.0, radius: 0.2}
  torso_lift_link:
    - {x: -0.1, y: 0.0, z: 0.1, radius: 0.2}
    - {x: 0.0, y: 0.0, z: 0.3, radius: 0.2}
    - {x: 0.0, y: 0.0, z: 0.5, radius: 0.2}
  fixed_bellows_link:
    - {x: 0.0, y: 0.0, z: 0.0, radius: 0.01}
  shoulder_pan_link:
    - {x: 0.14, y: -0.06, z: -0.01, radius: 0.097}
    - {x: 0.14, y: 0.06, z: -0.01, radius: 0.097}
    - {x: 0.14, y: 0.00, z: -0.01, radius: 0.097}
  shoulder_lift_link:
    - {x: 0.13545, y: 0.0, z: 0.0, radius: 0.09}
  upperarm_roll_link:
    - {x: 0.06, y: 0.03, z: -0.0225, radius: 0.06}
    - {x: 0.06, y: -0.03, z: -0.0225, radius: 0.06}
    - {x: 0.06, y: -0.0, z: -0.0225, radius: 0.06}
    - {x: 0.11, y: -0.04, z: -0.035, radius: 0.05}
    - {x: 0.11, y: 0.04, z: -0.035, radius: 0.05}
    - {x: 0.11, y: 0.0, z: -0.035, radius: 0.05}
    - {x: 0.16, y: 0.03, z: -0.025, radius: 0.06}
    - {x: 0.16, y: -0.03, z: -0.025, radius: 0.06}
    - {x: 0.16, y: -0.0, z: -0.025, radius: 0.06}
    - {x: 0.21, y: 0.035, z: 0.0, radius: 0.06}
    - {x: 0.21, y: -0.035, z: 0.0, radius: 0.06}
  elbow_flex_link:
    - {x: 0.05, y: 0.0, z: -0.005, radius: 0.065}
  forearm_roll_link:
    - {x: 0.05, y: 0.025, z: -0.005, radius: 0.065}
    - {x: 0.05, y: -0.025, z: -0.005, radius: 0.065}
    - {x: 0.10, y: 0.0275, z: -0.005, radius: 0.065}
    - {x: 0.10, y: -0.0275, z: -0.005, radius: 0.065}
    - {x: 0.15, y: 0.0225, z: -0.015, radius: 0.05}
    - {x: 0.15, y: -0.0225, z: -0.015, radius: 0.05}
    - {x: 0.19, y: 0.03, z: -0.015, radius: 0.05}
    - {x: 0.19, y: -0.03, z: -0.015, radius: 0.05}
    - {x: 0.24, y: 0.03, z: 0.00, radius: 0.05}
    - { x: 0.24, y: -0.03, z: 0.0, radius: 0.05}
  wrist_roll_link:
    - {x: 0.055, y: -0.03, z: 0.00, radius: 0.04}
    - {x: 0.055, y: 0.0, z: 0.00, radius: 0.04}
    - {x: 0.055, y: 0.03, z: 0.00, radius: 0.04}
    - {x: 0.025, y: 0.02, z: 0.00, radius: 0.04}
    - {x: 0.025, y: -0.02, z: 0.00, radius: 0.04}
  wrist_flex_link:
    - {x: 0.0, y: 0.0, z: 0.0, radius: 0.01}
  left_gripper_finger_link:
    - {x: -0.02, y: 0.005, z: 0.00, radius: 0.015}
    - {x: -0.01, y: 0.005, z: 0.00, radius: 0.015}
    - {x: 0.00, y: 0.005, z: 0.00, radius: 0.015}
    - {x: 0.01, y: 0.005, z: 0.00, radius: 0.015}
    - {x: 0.02, y: 0.005, z: 0.00, radius: 0.015}
  right_gripper_finger_link:
    - {x: -0.02, y: -0.005, z: 0.00, radius: 0.015}
    - {x: -0.01,   y: -0.005, z: 0.00, radius: 0.015}
    - {x: 0.0, y: -0.005, z: 0.00, radius: 0.015}
    - {x: 0.01, y: -0.005, z: 0.00, radius: 0.015}
    - {x: 0.02, y: -0.005, z: 0.00, radius: 0.015}
  head_pan_link:
    - {x: 0.0, y: 0.0, z: 0.0, radius: 0.15}
  head_tilt_link:
    - {x: 0.0, y: 0.0, z: 0.01, radius: 0.0825}
    - {x: 0.0, y: -0.085, z: 0.01, radius: 0.0825}
    - {x: 0.0, y: 0.085, z: 0.01, radius: 0.0825}